//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMChurch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Address
    {
        public Address()
        {
            this.MemberContacts = new HashSet<MemberContact>();
        }
    
        public long AddressID { get; set; }
    [Display(Name="Address")]
        public string Address1 { get; set; }
        [Display(Name="Apt #, Suite #, etc")]
        public string Address2 { get; set; }
        public Nullable<int> ZipCode { get; set; }
    
        public virtual ICollection<MemberContact> MemberContacts { get; set; }
    }
}
