//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMChurch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Email
    {
        public Email()
        {
            this.MemberContacts = new HashSet<MemberContact>();
        }
    
        public long EmailID { get; set; }
        [DataType(DataType.EmailAddress)]
        [Display(Name="Email")]
        public string EmailAddress { get; set; }
        public long ContactTypeID { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual ICollection<MemberContact> MemberContacts { get; set; }
    }
}
