//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMChurch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MemberGiving
    {
        public long MemberGivingID { get; set; }
        public long MemberID { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<int> Tithes { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<int> Offering { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
