//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMChurch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;


    public partial class Member
    {
        public Member()
        {
            this.MemberContacts = new HashSet<MemberContact>();
            this.MemberGivings = new HashSet<MemberGiving>();
        }

        public long MemberID { get; set; }
        [Display(Name = "First")]
        public string FirstName { get; set; }
        [Display(Name = "Last")]
        public string LastName { get; set; }
        public long MemberTypeID { get; set; }

        public virtual ICollection<MemberContact> MemberContacts { get; set; }

        public virtual MemberType MemberType { get; set; }
        public virtual ICollection<MemberGiving> MemberGivings { get; set; }

      
    }


}
