//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMChurch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Phone
    {
        public Phone()
        {
            this.MemberContacts = new HashSet<MemberContact>();
        }
    
        public long PhoneID { get; set; }
        [Display(Name="Area Code")]
        public Nullable<int> AreaCode { get; set; }
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> Number { get; set; }
        public long ContactTypeID { get; set; }
    
        public virtual ContactType ContactType { get; set; }
        public virtual ICollection<MemberContact> MemberContacts { get; set; }
    }
}
