//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FCMChurch.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    
    public partial class StateName
    {
        public StateName()
        {
            this.MemberContacts = new HashSet<MemberContact>();
        }
    
        public long StateNameID { get; set; }
        public string State { get; set; }
        [Display(Name="Abbreviation")]
        public string StateAbbreviation { get; set; }
    
        public virtual ICollection<MemberContact> MemberContacts { get; set; }
    }
}
